name: Test

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages_directory_listing:

    runs-on: ubuntu-latest
    name: Pages Directory Listing

    steps:

      # Step 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # branch to check out
          ref: main

      # Step 2. Generate the artifact
      - name: Generate Directory Listings
        uses: Zeyu-Xie/Lavender-Dir-Listing@v0.0.29
        with:
          # directory to generate the artifact
          FOLDER: .
      # Step 3. Compress
      - name: Create artifact
        run: tar -czf artifact.tar.gz ./web --hard-dereference

      # Step 4. Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact.tar.gz
  
  # Job 2. Deploy New Site
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    name: Deploy New Site
    needs: pages_directory_listing

    steps:
      
      # Step 1. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: artifact
