name: Test

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages_directory_listing:

    runs-on: ubuntu-latest
    name: Pages Directory Listing

    steps:

      # Step 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          # branch to check out
          ref: main

      # Step 2. Generate the artifact
      - name: Generate Directory Listings
        uses: Zeyu-Xie/Lavender-Dir-Listing@v0.0.29
        with:
          # directory to generate the artifact
          FOLDER: .
      
      # Step 3. Compress
      - name: Create artifact
        run: |
          sudo rm ./web/README.md
          sudo mv ./web ./_site
          ls -R .
          tar -czf artifact.tar.gz ./_site --hard-dereference
          

      # Step 4. Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact.tar.gz

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          name: artifact
          path: ./_site
