name: Test

on: [push]

jobs:
  pages_directory_listing:

    runs-on: ubuntu-latest
    name: Pages Directory Listing

    steps:

      # Step 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # branch to check out
          ref: main

      # Step 2. Generate the artifact
      - name: Generate Directory Listings
        uses: Zeyu-Xie/Lavender-Dir-Listing@v0.0.16
        with:
          # directory to generate the artifact
          FOLDER: ./

      # Step 3. Upload the artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '/web'
